const {chromium}=require('playwright');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
fs.mkdirSync(path.join(root,'.build'),{recursive:true});
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.md':'text/plain'};
const server=http.createServer((req,res)=>{
  const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
  if(!pathname.startsWith('/wkolon/'))return res.writeHead(404).end();
  const name=pathname.slice('/wkolon/'.length)||'index.html';
  const file=path.resolve(root,name);
  if(!file.startsWith(root+path.sep))return res.writeHead(403).end();
  fs.readFile(file,(error,data)=>{if(error)return res.writeHead(404).end();res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'}).end(data);});
});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 let browser;
 try{
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1050}});
  const page=await context.newPage();page.setDefaultTimeout(15000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const base=`http://127.0.0.1:${server.address().port}/wkolon/`;
  await page.goto(base+'#creation');
  const editor=page.locator('#creator-modal');
  const step=async i=>{await editor.locator(`[data-step="${i}"]`).click();};
  await editor.locator('[data-field="name"]').waitFor();
  assert.equal(await page.locator('link[rel="icon"]').getAttribute('href'),'./favicon.png');
  assert.equal(await page.locator('.module').count(),17);
  assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).fontFamily),'"Times New Roman", Times, serif');
  await editor.locator('[data-field="name"]').fill('Kera Voss');
  await editor.locator('[data-class="0"]').selectOption('class:soldier');
  await step(2);
  for(const id of ['endurance','initiative','mechanics','perception','pilot'])await editor.locator(`[data-trained="skill:${id}"]`).check();
  await step(3);
  await editor.locator('[data-choice="feat"][data-slot="0"][data-primary]').selectOption('feat:improved-defenses|');
  await editor.locator('[data-choice="feat"][data-slot="1"][data-primary]').selectOption('feat:toughness|');
  await editor.locator('[data-choice="talent"]').selectOption('talent:armored-defense|');
  assert.equal(await page.locator('.validation').count(),0);
  await step(4);
  await editor.locator('[data-field="credits"]').fill('10000');await editor.locator('[data-field="credits"]').press('Tab');
  await page.screenshot({path:path.join(root,'.build/creator-desktop.png')});
  await editor.locator('#cr-done').click();
  await page.locator('nav a[href="#equipment"]').click();
  await page.locator('#equipment-catalog > summary').click();
  await page.locator('#purchase-item').selectOption('equipment:blaster-pistol');
  await page.locator('#purchase button[type="submit"]').click();
  assert.equal(await page.locator('main [data-field="credits"]').inputValue(),'9500');
  await page.locator('#purchase-item').selectOption('equipment:stormtrooper-armor');
  await page.locator('#purchase button[type="submit"]').click();
  assert.equal(await page.locator('main [data-field="credits"]').inputValue(),'1500');
  await page.locator('nav a[href="#overview"]').click();
  assert.equal(await page.locator('[data-defense="reflex"]').textContent(),'20');
  assert((await page.locator('main').textContent()).includes('3d6'));
  assert(!(await page.locator('#class-table').textContent()).includes('NaN'));
  await page.locator('#equipment-catalog > summary').click();
  await page.screenshot({path:path.join(root,'.build/overview-desktop.png'),fullPage:true});
  const downloadEvent=page.waitForEvent('download');await page.locator('#export-character').click();
  const download=await downloadEvent;const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
  assert.equal(exported.name,'Kera Voss');assert.equal(exported.credits,1500);assert.equal(exported.inventory.length,2);
  // The track uses pmcrwf's click-to-set and click-current-to-step-down behavior.
  assert.equal(await page.locator('#module-condition > h2').textContent(),'▾Condition Track');
  assert.equal(await page.locator('#condition-effect tbody tr').count(),6);
  assert.equal(await page.locator('select[data-field="condition"]').count(),0);
  assert.deepEqual(await page.locator('#condition-effect button').allTextContents(),[
    'Normal State (No Penalties)',
    '-1 Penalty to Defenses, Attacks, Ability Checks, and Skill Checks',
    '-2 Penalty to Defenses, Attacks, Ability Checks, and Skill Checks',
    '-5 Penalty to Defenses, Attacks, Ability Checks, and Skill Checks',
    'Move at Half Speed; -10 Penalty to Defenses, Attacks, Ability Checks, and Skill Checks',
    'Helpless (Unconscious)',
  ]);
  await page.locator('#condition-effect button[data-condition-step="0"]').click();
  assert.equal(await page.locator('#condition-level').inputValue(),'0');
  const initialAbilityBonus=Number(await page.locator('#module-abilities [data-roll]').first().getAttribute('data-roll'));
  const initialReflex=Number(await page.locator('[data-defense="reflex"]').textContent());
  const initialThreshold=await page.locator('#module-threshold .stat-big').textContent();
  const initialSpeed=await page.locator('#module-speed .stat-big').textContent();
  await page.locator('#condition-effect tr[data-condition-step="1"] td').last().click();
  assert.equal(await page.locator('#condition-level').inputValue(),'1');
  assert.equal(Number(await page.locator('[data-defense="reflex"]').textContent()),initialReflex-1);
  assert.equal(await page.locator('#condition-effect .condition-on').count(),1);
  assert.equal(Number(await page.locator('#module-abilities [data-roll]').first().getAttribute('data-roll')),initialAbilityBonus-1);
  assert.equal(await page.locator('#module-threshold .stat-big').textContent(),initialThreshold);
  await page.locator('#condition-effect tr[data-condition-step="4"] td').last().click();
  assert.equal(await page.locator('#condition-level').inputValue(),'4');
  assert.equal(Number(await page.locator('[data-defense="reflex"]').textContent()),initialReflex-10);
  assert.equal(Number(await page.locator('#module-speed .stat-big').textContent()),Math.floor(Number(initialSpeed)/2));
  assert.equal(await page.locator('#condition-effect .condition-on').count(),4);
  await page.locator('#condition-effect button[data-condition-step="5"]').click();
  assert.equal(await page.locator('#condition-effect .condition-on').count(),5);
  assert.equal(await page.locator('#module-attacks [data-roll]').isDisabled(),true);
  assert.equal(await page.locator('#module-abilities [data-roll]').first().isDisabled(),true);
  assert.equal(await page.locator('#module-skills [data-roll]').first().isDisabled(),true);
  await page.locator('#condition-effect button[data-condition-step="5"]').press('Enter');
  assert.equal(await page.locator('#condition-level').inputValue(),'4');
  assert.equal(await page.locator('#module-attacks [data-roll]').isDisabled(),false);
  await page.locator('#condition-effect button[data-condition-step="4"]').click();
  assert.equal(await page.locator('#condition-level').inputValue(),'3');
  assert.equal(Number(await page.locator('[data-defense="reflex"]').textContent()),initialReflex-5);
  assert.equal(await page.locator('#module-speed .stat-big').textContent(),initialSpeed);
  await page.reload();await page.locator('#condition-level').waitFor({state:'attached'});
  assert.equal(await page.locator('#condition-level').inputValue(),'3');
  assert.equal(await page.locator('#condition-effect .condition-current button').getAttribute('aria-pressed'),'true');
  await page.locator('#condition-effect button[data-condition-step="0"]').click();
  assert.equal(await page.locator('#condition-level').inputValue(),'0');
  assert.equal(await page.locator('#condition-effect .condition-on').count(),1);
  assert.equal(Number(await page.locator('[data-defense="reflex"]').textContent()),initialReflex);
  assert.equal(await page.locator('#module-force [data-field="forcePoints"]').getAttribute('aria-label'),'Force points');
  const copy=await page.locator('body').innerText();
  for(const removed of ['Equip a weapon in Equipment.','Pool on level up:','Untrained checks are limited','Maximum HP','Scores above are totals','Your inventory is empty.','All build choices complete'])assert(!copy.includes(removed),removed);
  assert.equal(await page.locator('#skill-calculations').getAttribute('open'),null);
  await page.locator('#skill-calculations summary').click();
  assert((await page.locator('#skill-calculations').textContent()).includes('half level'));
  await page.locator('#skill-calculations summary').click();
  // Bundled mechanics expand locally; default labels stay concise.
  assert.equal(await page.locator('main a[href*="swse.miraheze.org"]').count(),0);
  await page.locator('#module-skills [id="ref-skill:mechanics"] > summary').click();
  assert((await page.locator('#module-skills [id="ref-skill:mechanics"] .rules-ref-body').innerText()).includes('INT modifier'));
  await page.locator('#module-skills [id="ref-skill:mechanics"] > summary').click();
  await page.locator('#module-inventory [id="inventory-1-equipment:stormtrooper-armor"] > summary').click();
  assert((await page.locator('#module-inventory [id="inventory-1-equipment:stormtrooper-armor"] .rules-ref-body').innerText()).includes('Reflex +6'));
  await page.locator('#module-inventory [id="inventory-1-equipment:stormtrooper-armor"] > summary').click();
  // Math fields retain pmcrwf's relative adjustment and expression behavior.
  const hp=page.locator('#hp-cur');const initialHP=Number(await hp.inputValue());
  await hp.fill('-3');await hp.press('Tab');assert.equal(Number(await hp.inputValue()),initialHP-3);
  await hp.fill('20+5');await hp.press('Tab');assert.equal(await hp.inputValue(),'25');
  // Rolls share one persistent per-character event log and mirrored corner panel.
  await page.locator('#roll-mirror-close').click();
  await page.locator('#module-attacks [data-roll]').click();
  await page.locator('#roll-mirror').waitFor({state:'visible'});
  assert.equal(await page.locator('#roll-mirror-body .ev').count(),1);
  await page.locator('#roll-mirror-cmd').fill('4d6kh3+2');await page.locator('#roll-mirror-cmd').press('Enter');
  assert.equal(await page.locator('#roll-mirror-body .ev').count(),2);
  const grip=await page.locator('#roll-mirror-grip').boundingBox();
  assert(grip.width>=32 && grip.height>=32);
  const mirrorBefore=await page.locator('#roll-mirror').boundingBox();
  await page.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2);await page.mouse.down();
  await page.mouse.move(grip.x+grip.width/2-48,grip.y+grip.height/2-32,{steps:5});await page.mouse.up();
  assert((await page.locator('#roll-mirror').boundingBox()).width>=mirrorBefore.width+40);
  await page.locator('#roll-mirror').screenshot({path:path.join(root,'.build/rolls-resize-grip.png')});
  await page.locator('main [data-field="name"]').fill('Kera renamed');await page.reload();
  await page.locator('main [data-field="name"]').waitFor();
  assert.equal(await page.locator('main [data-field="name"]').inputValue(),'Kera renamed');
  assert.equal(await page.locator('#roll-mirror-body .ev').count(),2);
  await page.locator('#new-character').click();assert.equal(await editor.locator('[data-field="name"]').inputValue(),'');
  await editor.locator('#cr-done').click();assert.equal(await page.locator('#roll-mirror-body .ev').count(),0);assert.equal(await page.locator('#condition-level').inputValue(),'0');
  await page.locator('#roster button').first().click();assert.equal(await page.locator('main [data-field="name"]').inputValue(),'Kera renamed');
  assert.equal(await page.locator('#roll-mirror-body .ev').count(),2);
  const before=await page.locator('#roster button').count();
  await page.locator('#import-character').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":1,"name":"Bad"}')});
  await page.waitForFunction(()=>document.querySelector('#message')?.textContent.includes('Invalid character'));
  assert.equal(await page.locator('#roster button').count(),before);
  await page.locator('#import-character').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
  await page.waitForFunction(()=>document.querySelector('main [data-field="name"]')?.value==='Kera Voss');
  assert.equal(await page.locator('#roster button').count(),before+1);
  await page.locator('nav a[href="#advancement"]').click();
  await editor.locator('[data-action="add-level"]').click();
  await editor.locator('[data-choice="feat"][data-level="1"][data-primary]').selectOption('feat:skill-focus|');
  await editor.locator('[data-choice="feat"][data-level="1"][data-secondary]').selectOption('feat:skill-focus|skill:pilot');
  assert.equal(await page.locator('.validation').count(),0);
  await editor.locator('#next-class').selectOption('class:scout');await editor.locator('[data-action="add-level"]').click();
  await editor.locator('[data-choice="startingFeat"][data-level="2"][data-primary]').selectOption('feat:shake-it-off|');
  await editor.locator('[data-choice="feat"][data-level="2"][data-primary]').selectOption('feat:improved-damage-threshold|');
  await editor.locator('[data-choice="talent"][data-level="2"]').selectOption('talent:acute-senses|');
  assert.equal(await page.locator('.validation').count(),0);
  await editor.locator('#cr-done').click();
  await page.locator('#theme-select').selectOption({label:'Truesight Dark'});
  await page.waitForFunction(()=>getComputedStyle(document.body).backgroundColor==='rgb(22, 22, 26)');
  assert.equal(await page.evaluate(()=>localStorage.getItem('charsheet-theme')),'truesight-dark.css');
  await page.screenshot({path:path.join(root,'.build/overview-dark.png'),fullPage:true});
  // Layout preferences are independent of the sister site's layout, and survive character renders.
  await page.evaluate(()=>localStorage.setItem('charsheet-layout','{"sister":"unchanged"}'));
  await page.locator('#module-abilities .lay-collapse-btn').click();
  await page.locator('#lay-free').check();
  const previousPosition=await page.evaluate(()=>({...window.__layout.state.map.defenses}));
  const module=page.locator('#module-defenses');const box=await module.boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+12);await page.mouse.down();await page.mouse.move(box.x+box.width/2+32,box.y+44,{steps:5});await page.mouse.up();
  await page.locator('#lay-free').uncheck();
  const position=await page.evaluate(()=>window.__layout.state.map.defenses);
  assert(position.x!==previousPosition.x || position.y!==previousPosition.y,'layout drag moves the module');
  await page.reload();await page.locator('#module-defenses').waitFor();
  assert.equal(await page.locator('#module-abilities').evaluate(el=>el.classList.contains('lay-collapsed')),true);
  assert.deepEqual(await page.evaluate(()=>window.__layout.state.map.defenses),position);
  assert.equal(await page.evaluate(()=>localStorage.getItem('charsheet-layout')),'{"sister":"unchanged"}');
  // Printing expands folded modules and retains numerical roll buttons.
  await page.emulateMedia({media:'print'});
  assert.equal(await page.locator('#module-abilities .lay-body').isVisible(),true);
  assert.equal(await page.locator('#module-abilities button.roll').first().isVisible(),true);
  await page.emulateMedia({media:'screen'});
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:path.join(root,'.build/sheet-mobile.png'),fullPage:true});
  await page.locator('nav a[href="#creation"]').click();await step(1);
  await page.screenshot({path:path.join(root,'.build/creation-mobile.png')});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.keyboard.press('Escape');await editor.waitFor({state:'hidden'});
  await page.locator('nav a[href="#rules"]').click();await editor.getByRole('heading',{name:'Source revisions'}).waitFor();
  await editor.locator('#cr-done').click();await page.locator('#print').click();
  assert.equal(await editor.isVisible(),false);
  assert.deepEqual(errors,[]);
  console.log('Browser: Saga creation, purchases, defenses, persistence, import/export, advancement, sister themes, math fields, roll logs, layout drag/persistence/isolation, Condition Track, concise UI, larger roll resize grip, mobile and print passed');
  // Hosted cache uses a complete build, scoped to this site. Explicit registration tests it
  // on localhost; the production registration deliberately bypasses preview servers.
  await require('./generation-checks.cjs')(browser,base,root);
  const offlineContext=await browser.newContext();const offlinePage=await offlineContext.newPage();
  offlinePage.on('pageerror',error=>errors.push(error.message));
  await offlinePage.goto(base);await offlinePage.locator('#module-abilities').waitFor();
  assert.equal(await offlinePage.evaluate(async()=> (await navigator.serviceWorker.getRegistrations()).length),0);
  await offlinePage.evaluate(async()=>{
    await caches.open('pmcrwf-sentinel');await caches.open('wkolon-old');
    await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;
  });
  await offlinePage.waitForFunction(()=>navigator.serviceWorker.controller!==null);
  assert(await offlinePage.evaluate(async()=>!(await caches.keys()).includes('wkolon-old')));
  assert(await offlinePage.evaluate(async()=>(await caches.keys()).includes('pmcrwf-sentinel')));
  const cached=await offlinePage.evaluate(async()=> (await (await caches.open('wkolon-__BUILD__')).keys()).map(req=>req.url));
  for (const asset of ['data/core.json','src/math-fields.js','src/dice.js','src/ability-generation.js','src/rules-reference.js','css/themes/truesight-dark.css','layouts/flow.json']) assert(cached.some(url=>url.endsWith('/wkolon/'+asset)),asset);
  await offlinePage.locator('main [data-field="name"]').fill('Offline hero');
  await offlineContext.setOffline(true);await offlinePage.reload();await offlinePage.locator('#module-abilities').waitFor();
  assert.equal(await offlinePage.locator('main [data-field="name"]').inputValue(),'Offline hero');
  await offlinePage.locator('#theme-select').selectOption({label:'Truesight Dark'});
  await offlinePage.waitForFunction(()=>getComputedStyle(document.body).backgroundColor==='rgb(22, 22, 26)');
  await offlinePage.locator('[id="ref-skill:mechanics"] > summary').click();
  assert((await offlinePage.locator('[id="ref-skill:mechanics"] .rules-ref-body').innerText()).includes('INT modifier'));
  await offlineContext.close();assert.deepEqual(errors,[]);
  console.log('Browser: complete offline reload, themes, rules and sister cache isolation passed');
  // A fixture species tests droid classification without publishing invented droid mechanics.
  const droidPack=JSON.parse(fs.readFileSync(path.join(root,'data/core.json'),'utf8'));
  droidPack.species.push({...droidPack.species.find(s=>s.id==='species:human'),id:'species:droid-fixture',name:'Droid fixture',isDroid:true,reference:[{heading:'Fixture',text:'<img src=x onerror=alert(1)>',sourceId:'source:human'}]});
  const droidContext=await browser.newContext();const droidPage=await droidContext.newPage();
  await droidPage.route('**/data/core.json',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(droidPack)}));
  await droidPage.goto(base+'#creation');
  const droidEditor=droidPage.locator('#creator-modal');
  await droidEditor.locator('[data-field="species"]').selectOption('species:droid-fixture');
  assert.equal(await droidPage.locator('#condition-effect button[data-condition-step="5"]').textContent(),'Helpless (Disabled)');
  await droidEditor.locator('[id="creator-species-species:droid-fixture"] > summary').click();
  assert.equal(await droidEditor.locator('.rules-ref-body img').count(),0);
  assert((await droidEditor.locator('.rules-ref-body').first().innerText()).includes('<img src=x onerror=alert(1)>'));
  await droidEditor.locator('[data-field="species"]').selectOption('species:human');
  assert.equal(await droidPage.locator('#condition-effect button[data-condition-step="5"]').textContent(),'Helpless (Unconscious)');
  await droidContext.close();console.log('Browser: automatic organic/droid terminal wording passed');
  // Recovery preserves damaged storage until a backup and explicit replacement.
  const recoveryContext=await browser.newContext();const recoveryPage=await recoveryContext.newPage();
  await recoveryPage.goto(base);await recoveryPage.evaluate(()=>localStorage.setItem('wkolon-roster-v1','{broken'));
  await recoveryPage.reload();await recoveryPage.locator('#recovery').waitFor({state:'visible'});
  await recoveryPage.locator('main [data-field="name"]').fill('Recovery draft');
  await recoveryPage.waitForTimeout(400);
  assert.equal(await recoveryPage.evaluate(()=>localStorage.getItem('wkolon-roster-v1')),'{broken');
  assert.equal(await recoveryPage.locator('#replace-storage').isVisible(),false);
  console.log('Browser: corrupt-storage preservation passed');
  const quotaContext=await browser.newContext();
  await quotaContext.addInitScript(() => { const original = Storage.prototype.setItem; Storage.prototype.setItem=function(key,value){if(key==='wkolon-roster-v1')throw new DOMException('Quota exceeded','QuotaExceededError');return original.call(this,key,value);}; });
  const quotaPage=await quotaContext.newPage();await quotaPage.goto(base);await quotaPage.locator('main [data-field="name"]').fill('Quota hero');
  await quotaPage.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Save failed'));
  assert.equal(await quotaPage.locator('main [data-field="name"]').inputValue(),'Quota hero');
  const quotaDownload=quotaPage.waitForEvent('download');await quotaPage.locator('#export-character').click();const quotaFile=await quotaDownload;assert.equal(JSON.parse(fs.readFileSync(await quotaFile.path(),'utf8')).name,'Quota hero');
  await quotaContext.close();console.log('Browser: quota failure preserves exportable in-memory character');
  await recoveryContext.close();await context.close();
 }finally{if(browser)await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;server.close();});
