const {chromium}=require('playwright');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
fs.mkdirSync(path.join(root,'.build'),{recursive:true});
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.md':'text/plain'};
const server=http.createServer((req,res)=>{
  const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
  if(!pathname.startsWith('/wkolon/'))return res.writeHead(404).end();
  const name=pathname.slice('/wkolon/'.length)||'index.html';
  const file=path.resolve(root,name);
  if(!file.startsWith(root+path.sep))return res.writeHead(403).end();
  fs.readFile(file,(error,data)=>{if(error)return res.writeHead(404).end();res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'}).end(data);});
});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 let browser;
 try{
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1050}});
  const page=await context.newPage();page.setDefaultTimeout(15000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const base=`http://127.0.0.1:${server.address().port}/wkolon/`;
  await page.goto(base+'#creation');
  const editor=page.locator('#creator-modal');
  const step=async i=>{await editor.locator(`[data-step="${i}"]`).click();};
  await editor.locator('[data-field="name"]').waitFor();
  assert.equal(await page.locator('link[rel="icon"]').getAttribute('href'),'./favicon.png');
  assert.equal(await page.locator('.module').count(),17);
  assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).fontFamily),'"Times New Roman", Times, serif');
  await editor.locator('[data-field="name"]').fill('Kera Voss');
  await editor.locator('[data-class="0"]').selectOption('class:soldier');
  await step(2);
  for(const id of ['endurance','initiative','mechanics','perception','pilot'])await editor.locator(`[data-trained="skill:${id}"]`).check();
  await step(3);
  await editor.locator('[data-choice="feat"][data-slot="0"]').selectOption('feat:improved-defenses|');
  await editor.locator('[data-choice="feat"][data-slot="1"]').selectOption('feat:toughness|');
  await editor.locator('[data-choice="talent"]').selectOption('talent:armored-defense|');
  assert.equal(await page.locator('.ready').count(),1);
  await step(4);
  await editor.locator('[data-field="credits"]').fill('10000');await editor.locator('[data-field="credits"]').press('Tab');
  await page.screenshot({path:path.join(root,'.build/creator-desktop.png')});
  await editor.locator('#cr-done').click();
  await page.locator('nav a[href="#equipment"]').click();
  await page.locator('#equipment-catalog summary').click();
  await page.locator('#purchase-item').selectOption('equipment:blaster-pistol');
  await page.locator('#purchase button[type="submit"]').click();
  assert.equal(await page.locator('main [data-field="credits"]').inputValue(),'9500');
  await page.locator('#purchase-item').selectOption('equipment:stormtrooper-armor');
  await page.locator('#purchase button[type="submit"]').click();
  assert.equal(await page.locator('main [data-field="credits"]').inputValue(),'1500');
  await page.locator('nav a[href="#overview"]').click();
  assert.equal(await page.locator('[data-defense="reflex"]').textContent(),'20');
  assert((await page.locator('main').textContent()).includes('3d6'));
  assert(!(await page.locator('#class-table').textContent()).includes('NaN'));
  await page.locator('#equipment-catalog summary').click();
  await page.screenshot({path:path.join(root,'.build/overview-desktop.png'),fullPage:true});
  const downloadEvent=page.waitForEvent('download');await page.locator('#export-character').click();
  const download=await downloadEvent;const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
  assert.equal(exported.name,'Kera Voss');assert.equal(exported.credits,1500);assert.equal(exported.inventory.length,2);
  // Math fields retain pmcrwf's relative adjustment and expression behavior.
  const hp=page.locator('#hp-cur');const initialHP=Number(await hp.inputValue());
  await hp.fill('-3');await hp.press('Tab');assert.equal(Number(await hp.inputValue()),initialHP-3);
  await hp.fill('20+5');await hp.press('Tab');assert.equal(await hp.inputValue(),'25');
  // Rolls share one persistent per-character event log and mirrored corner panel.
  await page.locator('#roll-mirror-close').click();
  await page.locator('#module-attacks [data-roll]').click();
  await page.locator('#roll-mirror').waitFor({state:'visible'});
  assert.equal(await page.locator('#roll-mirror-body .ev').count(),1);
  await page.locator('#roll-mirror-cmd').fill('4d6kh3+2');await page.locator('#roll-mirror-cmd').press('Enter');
  assert.equal(await page.locator('#roll-mirror-body .ev').count(),2);
  await page.locator('main [data-field="name"]').fill('Kera renamed');await page.reload();
  await page.locator('main [data-field="name"]').waitFor();
  assert.equal(await page.locator('main [data-field="name"]').inputValue(),'Kera renamed');
  assert.equal(await page.locator('#roll-mirror-body .ev').count(),2);
  await page.locator('#new-character').click();assert.equal(await editor.locator('[data-field="name"]').inputValue(),'');
  await editor.locator('#cr-done').click();assert.equal(await page.locator('#roll-mirror-body .ev').count(),0);
  await page.locator('#roster button').first().click();assert.equal(await page.locator('main [data-field="name"]').inputValue(),'Kera renamed');
  assert.equal(await page.locator('#roll-mirror-body .ev').count(),2);
  const before=await page.locator('#roster button').count();
  await page.locator('#import-character').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":1,"name":"Bad"}')});
  await page.waitForFunction(()=>document.querySelector('#message')?.textContent.includes('Invalid character'));
  assert.equal(await page.locator('#roster button').count(),before);
  await page.locator('#import-character').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
  await page.waitForFunction(()=>document.querySelector('main [data-field="name"]')?.value==='Kera Voss');
  assert.equal(await page.locator('#roster button').count(),before+1);
  await page.locator('nav a[href="#advancement"]').click();
  await editor.locator('[data-action="add-level"]').click();
  await editor.locator('[data-choice="feat"][data-level="1"]').selectOption('feat:skill-focus|skill:pilot');
  assert.equal(await page.locator('.ready').count(),1);
  await editor.locator('#next-class').selectOption('class:scout');await editor.locator('[data-action="add-level"]').click();
  await editor.locator('[data-choice="startingFeat"][data-level="2"]').selectOption('feat:shake-it-off|');
  await editor.locator('[data-choice="feat"][data-level="2"]').selectOption('feat:improved-damage-threshold|');
  await editor.locator('[data-choice="talent"][data-level="2"]').selectOption('talent:acute-senses|');
  assert.equal(await page.locator('.ready').count(),1);
  await editor.locator('#cr-done').click();
  await page.locator('#theme-select').selectOption({label:'Truesight Dark'});
  await page.waitForFunction(()=>getComputedStyle(document.body).backgroundColor==='rgb(22, 22, 26)');
  assert.equal(await page.evaluate(()=>localStorage.getItem('charsheet-theme')),'truesight-dark.css');
  await page.screenshot({path:path.join(root,'.build/overview-dark.png'),fullPage:true});
  // Layout preferences are independent of the sister site's layout, and survive character renders.
  await page.evaluate(()=>localStorage.setItem('charsheet-layout','{"sister":"unchanged"}'));
  await page.locator('#module-abilities .lay-collapse-btn').click();
  await page.locator('#lay-free').check();
  const previousPosition=await page.evaluate(()=>({...window.__layout.state.map.defenses}));
  const module=page.locator('#module-defenses');const box=await module.boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+12);await page.mouse.down();await page.mouse.move(box.x+box.width/2+32,box.y+44,{steps:5});await page.mouse.up();
  await page.locator('#lay-free').uncheck();
  const position=await page.evaluate(()=>window.__layout.state.map.defenses);
  assert(position.x!==previousPosition.x || position.y!==previousPosition.y,'layout drag moves the module');
  await page.reload();await page.locator('#module-defenses').waitFor();
  assert.equal(await page.locator('#module-abilities').evaluate(el=>el.classList.contains('lay-collapsed')),true);
  assert.deepEqual(await page.evaluate(()=>window.__layout.state.map.defenses),position);
  assert.equal(await page.evaluate(()=>localStorage.getItem('charsheet-layout')),'{"sister":"unchanged"}');
  // Printing expands folded modules and retains numerical roll buttons.
  await page.emulateMedia({media:'print'});
  assert.equal(await page.locator('#module-abilities .lay-body').isVisible(),true);
  assert.equal(await page.locator('#module-abilities button.roll').first().isVisible(),true);
  await page.emulateMedia({media:'screen'});
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:path.join(root,'.build/sheet-mobile.png'),fullPage:true});
  await page.locator('nav a[href="#creation"]').click();await step(1);
  await page.screenshot({path:path.join(root,'.build/creation-mobile.png')});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.keyboard.press('Escape');await editor.waitFor({state:'hidden'});
  await page.locator('nav a[href="#rules"]').click();await editor.getByRole('heading',{name:'Source revisions'}).waitFor();
  await editor.locator('#cr-done').click();await page.locator('#print').click();
  assert.equal(await editor.isVisible(),false);
  assert.deepEqual(errors,[]);
  console.log('Browser: Saga creation, purchases, defenses, persistence, import/export, advancement, sister themes, math fields, roll logs, layout drag/persistence/isolation, mobile and print passed');
  // Hosted cache uses a complete build, scoped to this site. Explicit registration tests it
  // on localhost; the production registration deliberately bypasses preview servers.
  const offlineContext=await browser.newContext();const offlinePage=await offlineContext.newPage();
  offlinePage.on('pageerror',error=>errors.push(error.message));
  await offlinePage.goto(base);await offlinePage.locator('#module-abilities').waitFor();
  assert.equal(await offlinePage.evaluate(async()=> (await navigator.serviceWorker.getRegistrations()).length),0);
  await offlinePage.evaluate(async()=>{
    await caches.open('pmcrwf-sentinel');await caches.open('wkolon-old');
    await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;
  });
  await offlinePage.waitForFunction(()=>navigator.serviceWorker.controller!==null);
  assert(await offlinePage.evaluate(async()=>!(await caches.keys()).includes('wkolon-old')));
  assert(await offlinePage.evaluate(async()=>(await caches.keys()).includes('pmcrwf-sentinel')));
  const cached=await offlinePage.evaluate(async()=> (await (await caches.open('wkolon-__BUILD__')).keys()).map(req=>req.url));
  for (const asset of ['data/core.json','src/math-fields.js','src/dice.js','css/themes/truesight-dark.css','layouts/flow.json']) assert(cached.some(url=>url.endsWith('/wkolon/'+asset)),asset);
  await offlinePage.locator('main [data-field="name"]').fill('Offline hero');
  await offlineContext.setOffline(true);await offlinePage.reload();await offlinePage.locator('#module-abilities').waitFor();
  assert.equal(await offlinePage.locator('main [data-field="name"]').inputValue(),'Offline hero');
  await offlinePage.locator('#theme-select').selectOption({label:'Truesight Dark'});
  await offlinePage.waitForFunction(()=>getComputedStyle(document.body).backgroundColor==='rgb(22, 22, 26)');
  await offlineContext.close();assert.deepEqual(errors,[]);
  console.log('Browser: complete offline reload, themes, rules and sister cache isolation passed');
  // Recovery preserves damaged storage until a backup and explicit replacement.
  const recoveryContext=await browser.newContext();const recoveryPage=await recoveryContext.newPage();
  await recoveryPage.goto(base);await recoveryPage.evaluate(()=>localStorage.setItem('wkolon-roster-v1','{broken'));
  await recoveryPage.reload();await recoveryPage.locator('#recovery').waitFor({state:'visible'});
  await recoveryPage.locator('main [data-field="name"]').fill('Recovery draft');
  await recoveryPage.waitForTimeout(400);
  assert.equal(await recoveryPage.evaluate(()=>localStorage.getItem('wkolon-roster-v1')),'{broken');
  assert.equal(await recoveryPage.locator('#replace-storage').isVisible(),false);
  console.log('Browser: corrupt-storage preservation passed');
  const quotaContext=await browser.newContext();
  await quotaContext.addInitScript(() => { const original = Storage.prototype.setItem; Storage.prototype.setItem=function(key,value){if(key==='wkolon-roster-v1')throw new DOMException('Quota exceeded','QuotaExceededError');return original.call(this,key,value);}; });
  const quotaPage=await quotaContext.newPage();await quotaPage.goto(base);await quotaPage.locator('main [data-field="name"]').fill('Quota hero');
  await quotaPage.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Save failed'));
  assert.equal(await quotaPage.locator('main [data-field="name"]').inputValue(),'Quota hero');
  const quotaDownload=quotaPage.waitForEvent('download');await quotaPage.locator('#export-character').click();const quotaFile=await quotaDownload;assert.equal(JSON.parse(fs.readFileSync(await quotaFile.path(),'utf8')).name,'Quota hero');
  await quotaContext.close();console.log('Browser: quota failure preserves exportable in-memory character');
  await recoveryContext.close();await context.close();
 }finally{if(browser)await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;server.close();});
