const {chromium}=require('playwright');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
fs.mkdirSync(path.join(root,'.build'),{recursive:true});
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.md':'text/plain'};
const server=http.createServer((req,res)=>{
  const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
  if(!pathname.startsWith('/wkolon/'))return res.writeHead(404).end();
  const name=pathname.slice('/wkolon/'.length)||'index.html';
  const file=path.resolve(root,name);
  if(!file.startsWith(root+path.sep))return res.writeHead(403).end();
  fs.readFile(file,(error,data)=>{if(error)return res.writeHead(404).end();res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'}).end(data);});
});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 let browser;
 try{
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1050}});
  const page=await context.newPage();page.setDefaultTimeout(15000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const base=`http://127.0.0.1:${server.address().port}/wkolon/`;
  await page.goto(base+'#creation');
  await page.locator('[data-field="name"]').waitFor();
  assert.equal(await page.locator('link[rel="icon"]').getAttribute('href'),'./favicon.png');
  // Downscale the square favicon for browser tabs. This only resamples the built-in output.
  await page.evaluate(async()=>{
    const img=new Image();img.src='./favicon.png';await img.decode();
    const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;
    canvas.getContext('2d').drawImage(img,0,0,128,128);
    window.__favicon128=canvas.toDataURL('image/png').split(',')[1];
  });
  if(process.env.WKOLON_OPTIMIZE_ICON==='1')fs.writeFileSync(path.join(root,'favicon.png'),Buffer.from(await page.evaluate(()=>window.__favicon128),'base64'));
  await page.locator('[data-field="name"]').fill('Kera Voss');
  await page.locator('[data-class="0"]').selectOption('class:soldier');
  for(const id of ['endurance','initiative','mechanics','perception','pilot'])await page.locator(`[data-trained="skill:${id}"]`).check();
  await page.locator('[data-choice="feat"][data-slot="0"]').selectOption('feat:improved-defenses|');
  await page.locator('[data-choice="feat"][data-slot="1"]').selectOption('feat:toughness|');
  await page.locator('[data-choice="talent"]').selectOption('talent:armored-defense|');
  assert.equal(await page.locator('.ready').count(),1);
  await page.locator('[data-field="credits"]').fill('10000');await page.locator('[data-field="credits"]').press('Tab');
  await page.locator('nav a[href="#equipment"]').click();
  await page.locator('#purchase-item').selectOption('equipment:blaster-pistol');
  await page.locator('#purchase button[type="submit"]').click();
  assert.equal(await page.locator('[data-field="credits"]').inputValue(),'9500');
  await page.locator('#purchase-item').selectOption('equipment:stormtrooper-armor');
  await page.locator('#purchase button[type="submit"]').click();
  assert.equal(await page.locator('[data-field="credits"]').inputValue(),'1500');
  await page.locator('nav a[href="#overview"]').click();
  assert.equal(await page.locator('.defense-card strong').first().textContent(),'20');
  assert((await page.locator('main').textContent()).includes('3d6'));
  await page.screenshot({path:path.join(root,'.build/overview-desktop.png'),fullPage:true});
  const downloadEvent=page.waitForEvent('download');await page.locator('#export-character').click();
  const download=await downloadEvent;const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
  assert.equal(exported.name,'Kera Voss');assert.equal(exported.credits,1500);assert.equal(exported.inventory.length,2);
  // Rapid reload must flush pending writes from pagehide.
  await page.locator('nav a[href="#creation"]').click();
  await page.locator('[data-field="name"]').fill('Kera renamed');await page.reload();
  assert.equal(await page.locator('[data-field="name"]').inputValue(),'Kera renamed');
  await page.locator('#new-character').click();assert.equal(await page.locator('[data-field="name"]').inputValue(),'');
  await page.locator('#roster button').first().click();assert.equal(await page.locator('[data-field="name"]').inputValue(),'Kera renamed');
  const before=await page.locator('#roster button').count();
  await page.locator('#import-character').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":1,"name":"Bad"}')});
  await page.waitForFunction(()=>document.querySelector('#message')?.textContent.includes('Invalid character'));assert.equal(await page.locator('#roster button').count(),before);assert((await page.locator('#message').textContent()).includes('Invalid character'));
  await page.locator('#import-character').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
  await page.waitForFunction(()=>document.querySelector('[data-field="name"]')?.value==='Kera Voss');
  assert.equal(await page.locator('#roster button').count(),before+1);
  await page.locator('nav a[href="#advancement"]').click();
  await page.locator('[data-action="add-level"]').click();
  await page.locator('[data-choice="feat"][data-level="1"]').selectOption('feat:skill-focus|skill:pilot');
  assert.equal(await page.locator('.ready').count(),1);
  await page.locator('#next-class').selectOption('class:scout');await page.locator('[data-action="add-level"]').click();
  await page.locator('[data-choice="startingFeat"][data-level="2"]').selectOption('feat:shake-it-off|');
  await page.locator('[data-choice="feat"][data-level="2"]').selectOption('feat:improved-damage-threshold|');
  await page.locator('[data-choice="talent"][data-level="2"]').selectOption('talent:acute-senses|');
  assert.equal(await page.locator('.ready').count(),1);
  await page.locator('#theme').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  await page.setViewportSize({width:390,height:844});await page.locator('nav a[href="#creation"]').click();
  await page.screenshot({path:path.join(root,'.build/creation-mobile.png'),fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.locator('nav a[href="#rules"]').click();await page.getByRole('heading',{name:'Source revisions'}).waitFor();assert((await page.locator('main').textContent()).includes('Source revisions'));
  await page.locator('#print').click();assert.equal(await page.locator('nav a[aria-current="page"]').getAttribute('href'),'#overview');
  assert.deepEqual(errors,[]);
  console.log('Browser: creation, valid build, purchases, defenses, rapid reload, roster, import/export, advancement, themes, mobile width, print and Pages subpath passed');
  // Recovery preserves damaged storage until a backup and explicit replacement.
  const recoveryContext=await browser.newContext();const recoveryPage=await recoveryContext.newPage();
  await recoveryPage.goto(base);await recoveryPage.evaluate(()=>localStorage.setItem('wkolon-roster-v1','{broken'));
  await recoveryPage.reload();await recoveryPage.locator('#recovery').waitFor({state:'visible'});
  await recoveryPage.locator('[data-field="name"]').fill('Recovery draft');
  await recoveryPage.waitForTimeout(400);
  assert.equal(await recoveryPage.evaluate(()=>localStorage.getItem('wkolon-roster-v1')),'{broken');
  assert.equal(await recoveryPage.locator('#replace-storage').isVisible(),false);
  console.log('Browser: corrupt-storage preservation passed');
  const quotaContext=await browser.newContext();
  await quotaContext.addInitScript(() => { const original = Storage.prototype.setItem; Storage.prototype.setItem=function(key,value){if(key==='wkolon-roster-v1')throw new DOMException('Quota exceeded','QuotaExceededError');return original.call(this,key,value);}; });
  const quotaPage=await quotaContext.newPage();await quotaPage.goto(base);await quotaPage.locator('[data-field="name"]').fill('Quota hero');
  await quotaPage.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Save failed'));
  assert.equal(await quotaPage.locator('[data-field="name"]').inputValue(),'Quota hero');
  const quotaDownload=quotaPage.waitForEvent('download');await quotaPage.locator('#export-character').click();const quotaFile=await quotaDownload;assert.equal(JSON.parse(fs.readFileSync(await quotaFile.path(),'utf8')).name,'Quota hero');
  await quotaContext.close();console.log('Browser: quota failure preserves exportable in-memory character');
  await recoveryContext.close();await context.close();
 }finally{if(browser)await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;server.close();});
