const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {randomUUID}=require('node:crypto');
module.exports=async function checkCombat(browser,base,root){
 const pack=JSON.parse(fs.readFileSync(path.join(root,'data/core.json'),'utf8'));
 const item=id=>({id:'equipment:'+id,uid:randomUUID(),quantity:1,equipped:true,twoHanded:false,attackMod:0,damageMod:0});
 const c={schemaVersion:1,ruleset:{id:pack.id,version:pack.version},id:randomUUID(),name:'Kera Voss',player:'',species:'species:human',abilityMethod:'standard',abilities:{str:15,dex:14,con:13,int:12,wis:10,cha:8},pointBudget:25,trainedSkills:['endurance','initiative','mechanics','perception','pilot'].map(s=>'skill:'+s),levels:[{classId:'class:soldier',hpRoll:null,feats:[{id:'feat:improved-defenses'},{id:'feat:toughness'}],talent:{id:'talent:armored-defense'},startingFeat:null,abilityIncreases:[],trainedSkills:[]}],inventory:[item('knife'),item('blaster-pistol'),item('blaster-pistol')],credits:250,currentHP:null,forcePoints:5,condition:0,languages:'Huttese',notes:'',modifiers:{reflex:0,fortitude:0,will:0,hp:0,threshold:0,attack:0,damage:0}};
 const context=await browser.newContext({viewport:{width:1300,height:1000},acceptDownloads:true});
 try{
  await context.addInitScript(c=>{if(!localStorage.getItem('wkolon-roster-v1'))localStorage.setItem('wkolon-roster-v1',JSON.stringify({schemaVersion:1,activeId:c.id,characters:[c]}));},c);
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);await page.locator('#module-routines').waitFor();
  const set=async(selector,value)=>{const el=page.locator(selector);await el.fill(String(value));await el.press('Tab');await page.waitForFunction(({selector,value})=>document.querySelector(selector)?.value===String(value),{selector,value});};
  const field=(key)=>`main [data-field="${key}"]`;
  const value=key=>page.locator(field(key)).inputValue();
  const saved=()=>page.evaluate(()=>{const r=JSON.parse(localStorage.getItem('wkolon-roster-v1'));return r.characters.find(c=>c.id===r.activeId);});
  await set(field('protection.srMax'),20);assert.equal(await value('protection.sr'),'20');
  await set(field('protection.dr'),5);
  const damage=async(amount,ignore=false)=>{await page.locator('#hp-damage-controls').evaluate(el=>el.open=true);await page.locator('[data-incoming-damage]').fill(String(amount));await page.locator('[data-ignore-dr]').setChecked(ignore);await page.locator('#apply-damage button').click();};
  await damage(30);assert.equal(await value('currentHP'),'27');assert.equal(await value('protection.sr'),'15');assert.equal(await value('protection.dr'),'5');
  await damage(20);assert.equal(await value('currentHP'),'27');assert.equal(await value('protection.sr'),'10');
  await damage(15,true);assert.equal(await value('currentHP'),'22');assert.equal(await value('protection.sr'),'5');
  assert.equal(await page.locator('#condition-level').inputValue(),'0');
  await set(field('xp'),500);assert.equal(await page.locator('.xp-bar .resource-fill').evaluate(el=>el.style.width),'50%');
  await set(field('darkSideScore'),5);assert.equal(await page.locator('.dark-side-bar .resource-fill').evaluate(el=>el.style.width),'50%');
  await set(field('forcePoints'),3);assert.equal(await page.locator('.force-bar .resource-fill').evaluate(el=>el.style.width),'60%');
  await page.locator('[data-combat="add-routine"]').click();await page.locator('[data-routine-field="name"]').fill('Double shot');
  await page.locator('[data-combat="add-step"]').click();
  await page.locator('[data-routine-field="attackId"]').selectOption(c.inventory[1].uid);
  await set('[data-routine-field="count"]',2);
  await page.locator('.routine-step details').evaluate(el=>el.open=true);
  await set('[data-routine-field="attackMod"]',-2);await set('[data-routine-field="damageMod"]',3);
  await page.locator('[data-combat="run"]').click();
  await page.waitForFunction(()=>document.querySelectorAll('#dicelog > .ev.rolling,#roll-mirror-body > .ev.rolling').length===2);
  await page.waitForFunction(()=>!document.querySelector('#dicelog > .ev.rolling'));
  assert.equal(await page.locator('#dicelog > .ev').first().locator('[data-sides="20"]').count(),2);
  assert((await page.locator('#dicelog > .ev').first().innerText()).includes('Reflex'));assert.equal(await page.locator('#dicelog > .ev').first().locator('details[open]').count(),0);
  await page.locator('#module-inventory [data-remove-item="0"]').click();assert.equal(await page.locator('[data-routine-field="attackId"]').inputValue(),c.inventory[1].uid);assert(await page.locator('[data-combat="run"]').isEnabled());
  await page.locator('#module-inventory [data-remove-item="0"]').click();assert(await page.locator('[data-combat="run"]').isDisabled());assert.equal(await page.locator('[data-routine-field="attackId"] option:checked').textContent(),'Attack unavailable');
  await page.locator('[data-routine-field="attackId"]').selectOption(c.inventory[2].uid);
  await page.locator('[data-combat="add-step"]').click();
  const firstId=await page.locator('.routine-step').first().getAttribute('data-step-id');
  await page.locator('.routine-step').last().locator('[data-combat="move-up"]').click();assert.equal(await page.locator('.routine-step').last().getAttribute('data-step-id'),firstId);
  await page.locator('.routine-step').first().locator('[data-combat="delete-step"]').click();
  await page.waitForTimeout(350);const before=await saved();await page.reload();await page.locator('#module-routines').waitFor();assert.equal((await saved()).routines[0].steps[0].attackId,c.inventory[2].uid);assert.equal(await value('xp'),'500');assert.equal(await value('protection.sr'),'5');
  const download=page.waitForEvent('download');await page.locator('#export-character').click();const exported=JSON.parse(fs.readFileSync(await (await download).path(),'utf8'));
  assert.deepEqual(exported.protection,before.protection);assert.deepEqual(exported.routines,before.routines);
  await page.locator('#import-character').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
  assert.equal(await page.locator('[data-routine-field="name"]').inputValue(),'Double shot');
  assert.equal(await page.locator('[data-routine-field="attackId"]').inputValue(),c.inventory[2].uid);
  await page.locator('#theme-select').selectOption({label:'Dracula Dark'});await page.waitForFunction(()=>getComputedStyle(document.body).backgroundColor==='rgb(40, 42, 54)');
  await page.locator('#module-hp').screenshot({path:path.join(root,'.build/protection-dracula.png')});
  await page.locator('#module-routines').screenshot({path:path.join(root,'.build/routine-dracula.png')});
  // The toolbar and browser shortcut produce the same print-only stat block.
  await page.evaluate(()=>{window.print=()=>{window.dispatchEvent(new Event('beforeprint'));window.__printed=true;};});
  await page.locator('#print').click();assert(!(await page.evaluate(()=>window.__printed)));
  assert(await page.locator('#stat-block-modal').isVisible());
  const plain=await page.locator('#stat-block-text').inputValue();assert(plain.includes('Defenses\n\nReflex Defense:'));assert(plain.includes('Double shot: 2 × Blaster Pistol'));assert(!plain.includes('<p>'));
  await context.grantPermissions(['clipboard-read','clipboard-write']);
  await page.locator('#stat-block-copy').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),plain);assert.equal(await page.locator('#stat-block-copy').innerText(),'Copied');
  // A denied clipboard API still offers the browser's selection-based fallback.
  await page.evaluate(()=>{navigator.clipboard.writeText=async()=>{throw new Error('denied');};document.execCommand=command=>command==='copy';});
  await page.locator('#stat-block-copy').click();assert.equal(await page.locator('#stat-block-text').evaluate(el=>el.selectionEnd-el.selectionStart),plain.length);
  await page.locator('#stat-block-print').click();assert(await page.evaluate(()=>window.__printed));
  await page.emulateMedia({media:'print'});assert(await page.locator('#print-stat-block').isVisible());assert(!(await page.locator('main').isVisible()));
  const block=await page.locator('#print-stat-block').innerText();
  for(const text of ['Kera Voss','Defenses','Offense','Base Stats','SR: 5/20','DR: 5','Hit Points: 22/32','Double shot: 2 × Blaster Pistol','Huttese'])assert(block.includes(text),text);
  assert.equal(await page.locator('#print-stat-block input,#print-stat-block button').count(),0);
  assert.equal(await page.locator('#print-stat-block').evaluate(el=>getComputedStyle(el).color),'rgb(0, 0, 0)');
  await page.screenshot({path:path.join(root,'.build/saga-stat-block.png'),fullPage:true});await page.pdf({path:path.join(root,'.build/saga-stat-block.pdf'),format:'Letter',printBackground:true});
  await page.emulateMedia({media:'screen'});assert(!(await page.locator('#print-stat-block').isVisible()));
  assert(await page.locator('#stat-block-modal').isVisible());await page.keyboard.press('Escape');assert(!(await page.locator('#stat-block-modal').isVisible()));
  await page.locator('#module-classes a[href="#advancement"]').click();await page.locator('[data-action="add-level"]').click();await page.locator('#cr-done').click();
  assert.equal(await value('forcePoints'),'6');assert((await page.locator('.xp-bar').innerText()).includes('3,000'));
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors,[]);
  console.log('Combat: DR/SR bars and damage, resource progress, routine modifiers/rolls/tumble, stable weapon references, reorder/removal, reload/export/import, Force Point advancement, mobile, stat-block text/clipboard/fallback and optional Saga print/PDF passed');
 }finally{await context.close();}
};
