const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
module.exports=async function checkFinishing(browser,base,root){
 const context=await browser.newContext({acceptDownloads:true,viewport:{width:1100,height:900}});
 try {
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'#creation');const body=page.locator('#cr-body');
  await body.locator('.cr-method').first().waitFor();
  const step=async n=>page.locator(`[data-step="${n}"]`).click();
  const finish=async()=>{if(!(await page.locator('#creator-modal').evaluate(el=>el.open)))await page.locator('#module-header a[href="#creation"]').click();await step(7);};
  const exportCharacter=async()=>{const event=page.waitForEvent('download');await page.locator('#export-character').click();return JSON.parse(fs.readFileSync(await(await event).path(),'utf8'));};
  await step(2);await body.locator('[data-class="0"]').selectOption('class:soldier');
  await step(0);for(const [i,a] of ['str','dex','con','int','wis','cha'].entries())await body.locator(`[data-generation-assign="${a}"]`).selectOption({value:String(i)});
  await finish();
  assert.equal(await body.locator('[data-field="notes"],[data-field="languages"]').count(),0);
  assert.equal(await body.locator('[data-trait]').count(),13);
  assert.equal(await body.locator('[data-story="kind"][value="none"]').isChecked(),true);
  const traits={age:'24',gender:'Female',height:'1.72',weight:'68.5',eyeColor:'Blue',hairColor:'Brown',skinColor:'Tan',appearance:'A weathered flight suit.',personality:'Curious, stubborn.',background:'A pilot raised on Dac.',goals:'Find my missing sister.'};
  await body.locator('[data-field="name"]').fill('Trait test');
  for(const [key,value] of Object.entries(traits))await body.locator(`[data-trait="${key}"]`).fill(value);
  await body.locator('[data-trait="era"]').selectOption('Clone Wars');
  await body.locator('[data-trait="heroType"]').selectOption('Exploration Heroes');
  await body.locator('[data-story="kind"][value="destiny"]').check();
  await body.locator('[data-story="id"]').selectOption('destiny:rescue');
  await body.locator('[data-story="details"]').fill('Save <my sister>.');
  assert.equal(await body.locator('[data-field="story.points"]').inputValue(),'1');
  await body.locator('.rules-ref-detail summary').click();
  assert((await body.locator('.rules-ref-body').innerText()).includes('Increase two Ability Scores of your choice by +1 each.'));
  await page.screenshot({path:path.join(root,'.build/finishing-destiny.png')});
  await page.locator('#cr-done').click();
  await page.locator('main [data-field="languages"]').fill('Huttese');
  await page.locator('main [data-field="notes"]').fill('Keep sheet notes.');
  await page.evaluate(()=>{window.addEventListener('beforeprint',()=>{window._traitsPrinted=document.querySelector('#print-stat-block')?.textContent;});});
  await page.pdf({path:path.join(root,'.build/heroic-traits.pdf'),format:'A4'});
  assert((await page.evaluate(()=>window._traitsPrinted)).includes('Save <my sister>.'));
  assert((await page.evaluate(()=>window._traitsPrinted)).includes('Keep sheet notes.'));
  assert.equal(await page.locator('#character-traits').getAttribute('open'),null);
  const destiny=await exportCharacter();assert.equal(destiny.story.kind,'destiny');assert.equal(destiny.story.id,'destiny:rescue');
  assert.equal(destiny.story.points,1);assert.equal(destiny.story.details,'Save <my sister>.');
  assert.equal(destiny.languages,'Huttese');assert.equal(destiny.notes,'Keep sheet notes.');
  for(const [key,value] of Object.entries(traits))assert.equal(destiny.heroicTraits[key],value);
  await page.reload();await finish();assert.equal(await body.locator('[data-trait="height"]').inputValue(),'1.72');
  assert.equal(await body.locator('[data-story="id"]').inputValue(),'destiny:rescue');
  await body.locator('[data-story="kind"][value="background"]').check();
  assert.equal(await body.locator('[data-field="story.points"],[data-story="details"]').count(),0);
  await body.locator('[data-story="id"]').selectOption('background:academic');
  const primary=body.locator('[data-background-skill="0"]');
  assert.equal((await primary.locator('option').allTextContents()).filter(n=>n==='Knowledge').length,1);
  assert.equal(await body.locator('[data-background-knowledge]').count(),0);
  await primary.selectOption('knowledge');
  assert.equal(await body.locator('[data-background-knowledge] option').count(),8);
  await body.locator('[data-background-knowledge]').selectOption('skill:knowledge-galactic-lore');
  await step(3);await body.locator('[data-knowledge-group="initial"]').check();
  await body.locator('[data-knowledge-field]').selectOption('skill:knowledge-galactic-lore');
  await finish();await body.locator('[data-story="id"]').selectOption('background:dac-origin');
  await body.locator('[data-background-skill="0"]').selectOption('skill:swim');
  assert.equal(await body.locator('[data-background-skill="1"] option[value="skill:swim"]').isDisabled(),true);
  await body.locator('[data-background-skill="1"]').selectOption('skill:persuasion');
  await body.locator('[data-story="language"]').selectOption('Quarrenese');
  assert.equal(await body.locator('[data-trait="background"]').inputValue(),'A pilot raised on Dac.');
  await page.screenshot({path:path.join(root,'.build/finishing-background.png')});
  await page.locator('#cr-done').click();const background=await exportCharacter();
  assert.deepEqual(background.story,{kind:'background',id:'background:dac-origin',skills:['skill:swim','skill:persuasion'],language:'Quarrenese'});
  assert((await page.locator('#module-header').innerText()).includes('Quarrenese'));
  await page.reload();await finish();assert.equal(await body.locator('[data-story="id"]').inputValue(),'background:dac-origin');
  assert.equal(await body.locator('[data-background-skill="1"]').inputValue(),'skill:persuasion');
  await body.locator('[data-story="kind"][value="none"]').check();
  assert.equal(await body.locator('[data-story="id"]').count(),0);
  await page.locator('#cr-done').click();assert.deepEqual((await exportCharacter()).story,{kind:'none'});
  assert(!(await page.locator('#module-header').innerText()).includes('Quarrenese'));
  // A Destiny gains a point on advancement and keeps a valid cap when a level is removed.
  await finish();await body.locator('[data-story="kind"][value="destiny"]').check();
  await body.locator('[data-story="id"]').selectOption('destiny:discovery');await page.locator('#cr-done').click();
  await page.locator('#module-classes a[href="#advancement"]').click();await body.locator('[data-action="add-level"]').click();
  await page.locator('#cr-done').click();assert.equal((await exportCharacter()).story.points,2);
  await page.locator('#module-classes a[href="#advancement"]').click();await body.locator('[data-action="undo-level"]').click();
  await page.locator('#confirm-dialog button[value="confirm"]').click();await page.locator('#cr-done').click();
  assert.equal((await exportCharacter()).story.points,1);
  // Old saved character files remain importable without new traits or story fields.
  const old=structuredClone(destiny);delete old.heroicTraits;delete old.story;old.name='Older file';
  await page.locator('#import-character').setInputFiles({name:'older.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(old))});
  await page.waitForFunction(()=>document.querySelector('main [data-field="name"]')?.value==='Older file');
  await finish();assert.equal(await body.locator('[data-story="kind"][value="none"]').isChecked(),true);
  assert.equal(await body.locator('[data-trait="age"]').inputValue(),'');
  await body.locator('[data-trait="age"]').fill('24');
  await body.locator('[data-story="kind"][value="background"]').check();
  await body.locator('[data-story="id"]').selectOption('background:bankrupt');
  await body.locator('[data-background-skill="0"]').selectOption('skill:survival');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await body.evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);
  await page.screenshot({path:path.join(root,'.build/finishing-mobile.png')});
  await page.locator('#cr-done').click();
  if(base.startsWith('https:')) {
    await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);
    await context.setOffline(true);await page.reload();await finish();
    assert.equal(await body.locator('[data-trait="age"]').inputValue(),'24');
    assert.equal(await body.locator('[data-story="id"]').inputValue(),'background:bankrupt');
    await body.locator('.rules-ref-detail summary').click();
    assert((await body.locator('.rules-ref-body').innerText()).includes('urban or civilized environments'));
  }
  assert.deepEqual(errors,[]);
  console.log('Browser: Heroic Traits, exclusive Destiny/Background/Neither, secondary Knowledge choices, languages, points, export/reload and older files passed');
 } finally {await context.close();}
};
