const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
module.exports=async function checkGeneration(browser,base,root){
 const context=await browser.newContext({acceptDownloads:true,viewport:{width:1100,height:900}});
 try {
  const page=await context.newPage(), errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'#creation');
  const firstLoad=await page.evaluate(()=>performance.timeOrigin);
  const body=page.locator('#cr-body');
  await body.locator('[data-field="species"]').selectOption('species:duros');
  await body.locator('[data-class="0"]').selectOption('class:soldier');
  const step=async n=>page.locator(`[data-step="${n}"]`).click();
  const method=async m=>body.locator(`[data-crmethod="${m}"]`).click();
  await step(1);
  assert.equal(await body.locator('.cr-method').count(),4);
  await method('point-buy');
  assert.deepEqual(await body.locator('.cr-points').evaluateAll(es=>es.map(e=>e.value)),['8','8','8','8','8','8']);
  for(const [a,n] of [['str','18'],['con','15'],['dex','9']])await body.locator(`[data-generation-points="${a}"]`).selectOption(n);
  assert.equal(await body.locator('.budget').textContent(),'25 / 25 points');
  assert.equal(await body.locator('#cr-final-dex').textContent(),'11');
  assert.equal(await body.locator('#cr-final-con').textContent(),'13');
  await body.locator('[data-generation-points="dex"]').selectOption('10');
  assert.equal(await body.locator('.budget.error').textContent(),'26 / 25 points');
  await body.locator('[data-field="pointBudget"]').fill('30');
  assert.equal(await body.locator('.budget').textContent(),'26 / 30 points');
  await method('standard');
  assert.deepEqual(await body.locator('.cr-assign').evaluateAll(es=>es.map(e=>e.value)),['','','','','','']);
  assert.equal(await body.locator('.cr-pool').count(),6);
  for(const [i,a] of ['str','dex','con','int','wis','cha'].entries())await body.locator(`[data-generation-assign="${a}"]`).selectOption({value:String(i)});
  assert.equal(await body.locator('[data-generation-assign="dex"] option[value="0"]').isDisabled(),true);
  assert.equal(await body.locator('.cr-pool.used').count(),6);
  await body.locator('[data-generation-assign="str"]').selectOption('');
  assert.equal(await body.locator('[data-generation-assign="dex"] option[value="0"]').isDisabled(),false);
  await body.locator('[data-generation-assign="dex"]').selectOption('0');
  await body.locator('[data-generation-assign="str"]').selectOption('1');
  await method('manual');
  const manual=body.locator('[data-generation-manual="str"]');
  assert.equal(await manual.getAttribute('type'),'number');
  await manual.evaluate(el=>el._identityTest=true);
  await manual.fill('');await manual.pressSequentially('12');
  assert.equal(await manual.evaluate(el=>el._identityTest && el===document.activeElement),true);
  assert.equal(await body.locator('#cr-final-str').textContent(),'12');
  assert.equal(await body.locator('#cr-mod-str').textContent(),'+1');
  await page.locator('#cr-next').click();
  assert.equal(await body.locator('[data-trained]').count()>0,true); // blur must not swallow this click
  await page.locator('#cr-done').click();
  assert.equal(await page.locator('#module-abilities [data-ability="str"]').inputValue(),'12');
  await page.locator('nav a[href="#creation"]').click();await step(1);
  await method('rolled');
  assert.equal(await body.locator('.cr-pool').count(),0); // arriving at the method doesn't roll
  // Exercise equal low rolls: score captions can coincide with another pool index.
  await page.evaluate(()=>{const original=crypto.getRandomValues.bind(crypto);let i=0;crypto.getRandomValues=array=>{if(array instanceof Uint32Array && array.length===1){array[0]=[2,0,0,0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,0,0,0][i++%24];return array;}return original(array);};});
  await body.locator('[data-action="roll-abilities"]').click();
  const pool=(await body.locator('.cr-pool').allTextContents()).map(Number);
  assert.equal(pool.length,6);assert.deepEqual(pool,[5,12,12,12,12,5]);
  assert((await page.locator('#dicelog').textContent()).includes('4d6 drop lowest ×6'));
  for(const [i,a] of ['str','dex','con','int','wis','cha'].entries())await body.locator(`[data-generation-assign="${a}"]`).selectOption({value:String(i)});
  await page.screenshot({path:path.join(root,'.build/ability-generation.png')});
  await step(2);
  for(const a of ['initiative','pilot'])await body.locator(`[data-trained="skill:${a}"]`).check();
  await step(3);
  const primary=()=>body.locator('[data-choice="feat"][data-slot="0"][data-primary]');
  const secondary=()=>body.locator('[data-choice="feat"][data-slot="0"][data-secondary]');
  const names=await primary().locator('option').allTextContents();
  assert.equal(names.filter(n=>n==='Skill Focus').length,1);
  assert(!names.some(n=>/^Skill Focus \(/.test(n)));
  assert.equal(names.filter(n=>n==='Weapon Proficiency').length,1);
  assert(!names.some(n=>/^Weapon Proficiency \(/.test(n)));
  await primary().selectOption('feat:skill-focus|');
  assert.equal(await secondary().isVisible(),true);
  assert.deepEqual(await secondary().locator('option').allTextContents(),['Choose…','Initiative','Pilot']);
  await secondary().selectOption('feat:skill-focus|skill:pilot');
  await secondary().selectOption('');
  assert.equal(await primary().inputValue(),'feat:skill-focus|');
  await primary().selectOption('family:Weapon Proficiency');
  assert.deepEqual(await secondary().locator('option').allTextContents(),['Choose…','Lightsabers']);
  await page.screenshot({path:path.join(root,'.build/feat-secondary.png')});
  await secondary().selectOption('feat:weapon-proficiency-lightsabers|');
  await page.locator('#cr-done').click();
  const downloadEvent=page.waitForEvent('download');await page.locator('#export-character').click();
  const exported=JSON.parse(fs.readFileSync(await (await downloadEvent).path(),'utf8'));
  assert.deepEqual(exported.abilityGeneration.pool,pool);
  assert.deepEqual(Object.values(exported.abilityGeneration.assign),[0,1,2,3,4,5]);
  assert.deepEqual(exported.levels[0].feats[0],{id:'feat:weapon-proficiency-lightsabers'});
  if(base.startsWith('https:'))await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);
  assert.equal(await page.evaluate(()=>performance.timeOrigin),firstLoad);
  await page.reload();await page.locator('nav a[href="#creation"]').click();await step(1);
  assert.deepEqual((await body.locator('.cr-pool').allTextContents()).map(Number),pool);
  assert.deepEqual(await body.locator('.cr-assign').evaluateAll(es=>es.map(e=>e.value)),['0','1','2','3','4','5']);
  await step(0);await body.locator('[data-class="0"]').selectOption('class:scout');await step(2);
  assert.equal(await body.locator('.skill-picks').evaluate(el=>getComputedStyle(el).flexDirection),'column');
  assert.equal(await body.locator('[data-trained^="skill:knowledge-"]').count(),0);
  assert.equal(await body.locator('[data-knowledge-field]').count(),0);
  await body.locator('[data-knowledge-group="initial"]').check();
  assert.equal(await body.locator('[data-knowledge-field] option').count(),8);
  await body.locator('[data-knowledge-field]').selectOption('skill:knowledge-galactic-lore');
  await body.locator('[data-add-knowledge]').click();
  assert.equal(await body.locator('[data-knowledge-field]').count(),2);
  assert.equal(await body.locator('[data-knowledge-field]').nth(1).locator('option[value="skill:knowledge-galactic-lore"]').isDisabled(),true);
  await body.locator('[data-knowledge-field]').nth(1).selectOption('skill:knowledge-tactics');
  await page.screenshot({path:path.join(root,'.build/skills-secondary.png')});
  await page.locator('#cr-done').click();
  const skillDownloadEvent=page.waitForEvent('download');await page.locator('#export-character').click();
  const skillExport=JSON.parse(fs.readFileSync(await (await skillDownloadEvent).path(),'utf8'));
  assert(skillExport.trainedSkills.includes('skill:knowledge-galactic-lore'));
  assert(skillExport.trainedSkills.includes('skill:knowledge-tactics'));
  await page.reload();await page.locator('nav a[href="#creation"]').click();await step(2);
  assert.deepEqual(await body.locator('[data-knowledge-field]').evaluateAll(es=>es.map(e=>e.value)),['skill:knowledge-galactic-lore','skill:knowledge-tactics']);
  await body.locator('[data-knowledge-group="initial"]').uncheck();
  assert.equal(await body.locator('[data-knowledge-field]').count(),0);
  assert.deepEqual(errors,[]);
  console.log('Browser: pmcrwf ability generation, species adjustments, manual blur, saved roll pools and secondary feat choices passed');
 } finally {await context.close();}
};
